;;;; Regenerate data/ from an IANA tzdb release.
;;;;
;;;; Usage (CI — see .github/workflows/update-tzdata.yml):
;;;;   uses: egao1980/cl-repository/.github/actions/setup-client@main
;;;;   uses: egao1980/cl-repository/.github/actions/setup-roswell@main
;;;;   ros -l scripts/ci-install-update.lisp -q
;;;;   # stage cl-stack-ssl OpenSSL overlay (same as http-backend-dexador)
;;;;   ros -l scripts/update-tzdata.lisp -q            ; latest release
;;;;   ros -l scripts/update-tzdata.lisp -q -- 2026c   ; specific release
;;;;
;;;; Env:
;;;;   INCLUDE_BACKZONE=1  also compile pre-1970 backzone data (default off)
;;;;
;;;; HTTP via cl-stack-http × http-backend-async × event-backend-libuv (dogfood).
;;;; External tools are the database build special case only: tar, zic.
;;;; Assumes deps already installed (ci-install-update) and OpenSSL overlay staged.
;;;;
;;;; Produces:
;;;;   data/VERSION            tzdb release id (e.g. 2026c)
;;;;   data/zoneinfo/**        TZif files, canonical zones only (fat, full history)
;;;;   data/links.sexp         alias -> canonical map
;;;;   data/zone1970.tab       zone/country table
;;;;   data/leapseconds        leap second list
;;;;
;;;; data/abbreviations.sexp is regenerated by scripts/gen-abbreviations.lisp.

(setf *debugger-hook*
      (lambda (c h)
        (declare (ignore h))
        (format *error-output* "~&error: ~a~%" c)
        (uiop:quit 1)))

(setf asdf:*compile-file-failure-behaviour* :warn)

(defun call-with-ci-muffles (fn)
  #+sbcl
  (handler-bind ((sb-ext:defconstant-uneql
                  (lambda (c)
                    (declare (ignore c))
                    (let ((r (find-restart 'continue)))
                      (when r (invoke-restart r))))))
    (funcall fn))
  #-sbcl
  (funcall fn))

(call-with-ci-muffles (lambda () (asdf:load-system "cl-repository-client")))
(cl-repository-client/asdf-integration:configure-asdf-source-registry)
(cl-repository-client/asdf-integration:load-system-init-files)

(call-with-ci-muffles
 (lambda ()
   (asdf:load-system "cl-stack-ssl")
   (asdf:load-system "event-backend-libuv")
   (asdf:load-system "http-backend-async")
   (asdf:load-system "cl-stack-http")))

;; Package-qualified forms must be top-level *after* the loads above (reader).
(setf http-backend-async:*event-backend-maker*
      (lambda () (event-backend-libuv:make-libuv-backend)))
(setf cl-stack-http:*preferred-backend* :async)
(cl-stack-http:ensure-http-backend :async)

(defpackage #:tzdata-update
  (:use #:cl)
  (:local-nicknames (#:http #:cl-stack-http)))
(in-package #:tzdata-update)

(defparameter *repo-root*
  (uiop:pathname-parent-directory-pathname
   (uiop:pathname-directory-pathname *load-truename*)))

(defparameter *iana-base* "https://data.iana.org/time-zones")

;; Standard source set (see tzdb Makefile TDATA) + backward links.
(defparameter *sources*
  (append '("africa" "antarctica" "asia" "australasia" "europe"
            "northamerica" "southamerica" "etcetera" "backward" "factory")
          (when (equal (uiop:getenv "INCLUDE_BACKZONE") "1")
            '("backzone"))))

(defun run (command)
  "Run external COMMAND (list) — database build special case (tar, zic)."
  (uiop:run-program command :output *standard-output* :error-output *error-output*))

(defun tzdb-version-valid-p (version)
  (and (= (length version) 5)
       (every #'digit-char-p (subseq version 0 4))
       (lower-case-p (char version 4))))

(defun latest-tzdb-version ()
  (let ((response (http:get (format nil "~a/tzdb/version" *iana-base*))))
    (http:raise-for-status response)
    (string-trim '(#\Space #\Tab #\Newline #\Return) (http:response-text response))))

(defun fetch-and-extract (version workdir)
  (let ((tarball (merge-pathnames (format nil "tzdata~a.tar.gz" version) workdir)))
    (multiple-value-bind (path response)
        (http:download (format nil "~a/releases/tzdata~a.tar.gz" *iana-base* version)
                       tarball :overwrite t)
      (http:raise-for-status response)
      (run (list "tar" "-xzf"
                 (cl-stack-pathlib:as-namestring path)
                 "-C" (uiop:native-namestring workdir))))))

(defun compile-zoneinfo (workdir zoneinfo-dir)
  "Database build special case: delegate to zic (fat = full history + abbreviations)."
  (run (append (list "zic" "-b" "fat" "-d" (uiop:native-namestring zoneinfo-dir))
               (mapcar (lambda (s)
                         (uiop:native-namestring (merge-pathnames s workdir)))
                       *sources*))))

(defun whitespace-split (line)
  (let ((words '()) (start nil))
    (dotimes (i (length line))
      (let ((ws (member (char line i) '(#\Space #\Tab))))
        (cond ((and ws start) (push (subseq line start i) words) (setf start nil))
              ((not (or ws start)) (setf start i)))))
    (when start (push (subseq line start) words))
    (nreverse words)))

(defun harvest-links (workdir)
  "Collect (alias . canonical) from every Link line in *SOURCES*."
  (let ((links '()))
    (dolist (source *sources*)
      (with-open-file (in (merge-pathnames source workdir))
        (loop for line = (read-line in nil)
              while line
              do (let ((words (whitespace-split line)))
                   (when (and (equal (first words) "Link") (>= (length words) 3))
                     (push (cons (third words) (second words)) links))))))
    (sort (remove-duplicates links :test #'equal)
          #'string< :key #'car)))

(defun write-links (links path version)
  (with-open-file (out path :direction :output :if-exists :supersede)
    (format out ";; alias -> canonical zone id (generated from tzdb Link lines)~%")
    (format out ";; tzdb release: ~a~%(~%" version)
    (loop for (alias . canonical) in links
          do (format out "(~s . ~s)~%" alias canonical))
    (format out ")~%")))

(defun prune-aliases (zoneinfo-dir links)
  "Delete alias TZif files (zic wrote them as copies); drop emptied directories."
  (dolist (link links)
    (uiop:delete-file-if-exists (merge-pathnames (car link) zoneinfo-dir)))
  (labels ((prune-empty (dir)
             (mapc #'prune-empty (uiop:subdirectories dir))
             (when (and (null (uiop:directory-files dir))
                        (null (uiop:subdirectories dir)))
               (uiop:delete-empty-directory dir))))
    (mapc #'prune-empty (uiop:subdirectories zoneinfo-dir))))

(defun count-zone-files (dir)
  (let ((n 0))
    (uiop:collect-sub*directories
     dir (constantly t) (constantly t)
     (lambda (d) (incf n (length (uiop:directory-files d)))))
    n))

(let* ((args (uiop:command-line-arguments))
       (version (or (find-if #'tzdb-version-valid-p args)
                    (latest-tzdb-version)))
       (workdir (uiop:ensure-directory-pathname
                 (merge-pathnames (format nil "tzdata-update-~a-~d" version (random 100000))
                                  (uiop:temporary-directory))))
       (data-dir (merge-pathnames "data/" *repo-root*))
       (zoneinfo-dir (merge-pathnames "zoneinfo/" data-dir)))
  (unless (tzdb-version-valid-p version)
    (error "bad tzdb version: ~s" version))
  (format t "~&tzdb release: ~a~%" version)
  (ensure-directories-exist workdir)
  (unwind-protect
       (progn
         (fetch-and-extract version workdir)
         (ensure-directories-exist data-dir)
         (when (uiop:directory-exists-p zoneinfo-dir)
           (uiop:delete-directory-tree zoneinfo-dir :validate t))
         (compile-zoneinfo workdir zoneinfo-dir)
         (let ((links (harvest-links workdir)))
           (write-links links (merge-pathnames "links.sexp" data-dir) version)
           (prune-aliases zoneinfo-dir links)
           (dolist (f '("zone1970.tab" "leapseconds"))
             (uiop:copy-file (merge-pathnames f workdir) (merge-pathnames f data-dir)))
           (with-open-file (out (merge-pathnames "VERSION" data-dir)
                                :direction :output :if-exists :supersede)
             (write-line version out))
           (format t "~&zones: ~d~%links: ~d~%" (count-zone-files zoneinfo-dir) (length links))
           (format t "~&Now regenerate the abbreviation index:~%")
           (format t "  ros -l scripts/gen-abbreviations.lisp -q~%")))
    (uiop:delete-directory-tree workdir :validate t :if-does-not-exist :ignore)))

(uiop:quit 0)
